//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_CT_BAO_GIA
    {
        public int ID { get; set; }
        public string SO_BAO_GIA { get; set; }
        public string MA_HANG { get; set; }
        public string MA_DIEU_CHINH { get; set; }
        public string TEN_HANG { get; set; }
        public string HANG_SP { get; set; }
        public string ITEM_CODE { get; set; }
        public int SO_LUONG { get; set; }
        public string DVT { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal THANH_TIEN { get; set; }
        public string THOI_GIAN_GIAO_HANG { get; set; }
        public Nullable<decimal> GIA_LIST { get; set; }
        public double CHIET_KHAU { get; set; }
        public Nullable<decimal> DON_GIA_NHAP { get; set; }
        public Nullable<double> HE_SO_LOI_NHUAN { get; set; }
        public Nullable<decimal> DON_GIA_BAO_DI_NET { get; set; }
        public Nullable<decimal> THANH_TIEN_NET { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<decimal> CM { get; set; }
        public Nullable<decimal> DON_GIA_MOI { get; set; }
        public Nullable<double> THUE_TNDN { get; set; }
        public Nullable<decimal> TIEN_THUE_TNDN { get; set; }
        public Nullable<decimal> KHACH_NHAN_DUOC { get; set; }
        public decimal GIA_LIST_VAT { get; set; }
        public decimal GIA_NHAP_VAT { get; set; }
    
        public virtual BH_BAO_GIA BH_BAO_GIA { get; set; }
        public virtual HH HH { get; set; }
    }
}
