//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_DOI_TUONG
    {
        public string MA_LOAI_DOI_TUONG { get; set; }
        public string TEN_LOAI_DOI_TUONG { get; set; }
    }
}
