//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HH_COMMENTS
    {
        public int ID { get; set; }
        public System.DateTime NGAY_COMMENT { get; set; }
        public string NGUOI_COMMENT { get; set; }
        public string MA_HANG { get; set; }
        public string NOI_DUNG_COMMENT { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
    }
}
