//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_CONG_NO
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public System.DateTime NGAY_HACH_TOAN { get; set; }
        public string MA_NHAN_VIEN { get; set; }
        public string SO_CHUNG_TU { get; set; }
        public string SO_HOA_DON { get; set; }
        public string MA_HANG { get; set; }
        public string DIEN_GIAI { get; set; }
        public decimal PS_NO { get; set; }
        public decimal PS_CO { get; set; }
        public decimal SO_DU_NO { get; set; }
        public decimal SO_DU_CO { get; set; }
        public decimal SO_LUONG { get; set; }
        public System.DateTime HAN_THANH_TOAN { get; set; }
        public string GHI_CHU { get; set; }
        public string TUAN_CONG_NO { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual KH KH { get; set; }
    }
}
