//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_POLICY
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<decimal> CK { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public Nullable<decimal> CK_HISTORY_1 { get; set; }
        public Nullable<decimal> GIA_HISTORY_1 { get; set; }
        public Nullable<decimal> CK_HISTORY_2 { get; set; }
        public Nullable<decimal> GIA_HISTORY_2 { get; set; }
        public Nullable<decimal> CK_HISTORY_3 { get; set; }
        public Nullable<decimal> GIA_HISTORY_3 { get; set; }
        public string NGUOI_CAP_NHAT { get; set; }
    
        public virtual HH_NHOM_VTHH HH_NHOM_VTHH { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual KH KH { get; set; }
    }
}
