//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_THONG_KE_MUA_HANG
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MA_HANG { get; set; }
        public int SL_MUA { get; set; }
        public decimal DON_GIA_MUA { get; set; }
        public System.DateTime NGAY_MUA { get; set; }
        public string NHAN_VIEN_BAN_HANG { get; set; }
    
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual KH KH { get; set; }
    }
}
