//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_INIT_TACH_GOP_MA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHO_INIT_TACH_GOP_MA()
        {
            this.KHO_NHAT_KY_TACH_GOP_MA = new HashSet<KHO_NHAT_KY_TACH_GOP_MA>();
        }
    
        public int ID { get; set; }
        public string LOAI_TACH { get; set; }
        public string MA_HANG_GOC_1 { get; set; }
        public Nullable<int> SL_MA_GOC_1 { get; set; }
        public string MA_HANG_GOC_2 { get; set; }
        public Nullable<int> SL_MA_GOC_2 { get; set; }
        public string MA_HANG_GOC_3 { get; set; }
        public Nullable<int> SL_MA_GOC_3 { get; set; }
        public string MA_HANG_DICH_1 { get; set; }
        public Nullable<int> SL_MA_DICH_1 { get; set; }
        public string MA_HANG_DICH_2 { get; set; }
        public Nullable<int> SL_MA_DICH_2 { get; set; }
        public string MA_HANG_DICH_3 { get; set; }
        public Nullable<int> SL_MA_DICH_3 { get; set; }
        public string MA_HANG_DICH_4 { get; set; }
        public Nullable<int> SL_MA_DICH_4 { get; set; }
        public string MA_HANG_DICH_5 { get; set; }
        public Nullable<int> SL_MA_DICH_5 { get; set; }
        public string MA_HANG_DICH_6 { get; set; }
        public Nullable<int> SL_MA_DICH_6 { get; set; }
        public string MA_HANG_DICH_7 { get; set; }
        public Nullable<int> SL_MA_DICH_7 { get; set; }
        public string MA_HANG_DICH_8 { get; set; }
        public Nullable<int> SL_MA_DICH_8 { get; set; }
        public string MA_HANG_DICH_9 { get; set; }
        public Nullable<int> SL_MA_DICH_9 { get; set; }
        public string MA_HANG_DICH_10 { get; set; }
        public Nullable<int> SL_MA_DICH_10 { get; set; }
        public string MA_HANG_DICH_11 { get; set; }
        public Nullable<int> SL_MA_DICH_11 { get; set; }
        public string MA_HANG_DICH_12 { get; set; }
        public Nullable<int> SL_MA_DICH_12 { get; set; }
        public string MA_HANG_DICH_13 { get; set; }
        public Nullable<int> SL_MA_DICH_13 { get; set; }
        public string MA_HANG_DICH_14 { get; set; }
        public Nullable<int> SL_MA_DICH_14 { get; set; }
        public string MA_HANG_DICH_15 { get; set; }
        public Nullable<int> SL_MA_DICH_15 { get; set; }
        public string MA_HANG_DICH_16 { get; set; }
        public Nullable<int> SL_MA_DICH_16 { get; set; }
        public string MA_HANG_DICH_17 { get; set; }
        public Nullable<int> SL_MA_DICH_17 { get; set; }
        public string MA_HANG_DICH_18 { get; set; }
        public Nullable<int> SL_MA_DICH_18 { get; set; }
        public string MA_HANG_DICH_19 { get; set; }
        public Nullable<int> SL_MA_DICH_19 { get; set; }
        public string MA_HANG_DICH_20 { get; set; }
        public Nullable<int> SL_MA_DICH_20 { get; set; }
        public string MA_HANG_DICH_21 { get; set; }
        public Nullable<int> SL_MA_DICH_21 { get; set; }
        public string MA_HANG_DICH_22 { get; set; }
        public Nullable<int> SL_MA_DICH_22 { get; set; }
        public string MA_HANG_DICH_23 { get; set; }
        public Nullable<int> SL_MA_DICH_23 { get; set; }
        public string MA_HANG_DICH_24 { get; set; }
        public Nullable<int> SL_MA_DICH_24 { get; set; }
        public string MA_HANG_DICH_25 { get; set; }
        public Nullable<int> SL_MA_DICH_25 { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual HH HH1 { get; set; }
        public virtual HH HH2 { get; set; }
        public virtual HH HH3 { get; set; }
        public virtual HH HH4 { get; set; }
        public virtual HH HH5 { get; set; }
        public virtual HH HH6 { get; set; }
        public virtual HH HH7 { get; set; }
        public virtual HH HH8 { get; set; }
        public virtual HH HH9 { get; set; }
        public virtual HH HH10 { get; set; }
        public virtual HH HH11 { get; set; }
        public virtual HH HH12 { get; set; }
        public virtual HH HH13 { get; set; }
        public virtual HH HH14 { get; set; }
        public virtual HH HH15 { get; set; }
        public virtual HH HH16 { get; set; }
        public virtual HH HH17 { get; set; }
        public virtual HH HH18 { get; set; }
        public virtual HH HH19 { get; set; }
        public virtual HH HH20 { get; set; }
        public virtual HH HH21 { get; set; }
        public virtual HH HH22 { get; set; }
        public virtual HH HH23 { get; set; }
        public virtual HH HH24 { get; set; }
        public virtual HH HH25 { get; set; }
        public virtual HH HH26 { get; set; }
        public virtual HH HH27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_NHAT_KY_TACH_GOP_MA> KHO_NHAT_KY_TACH_GOP_MA { get; set; }
    }
}
