//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_GIU_HANG
    {
        public int ID { get; set; }
        public string SALES_GIU { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MA_HANG { get; set; }
        public System.DateTime NGAY_GIU { get; set; }
        public Nullable<System.DateTime> NGAY_XUAT { get; set; }
        public int SL_GIU { get; set; }
        public bool DA_XUAT { get; set; }
        public bool GIU_PO { get; set; }
        public bool HUY_DON_GIU { get; set; }
        public string TRUC_THUOC { get; set; }
        public string GHI_CHU { get; set; }
        public string DIA_CHI_XUAT { get; set; }
        public Nullable<int> ID_CT_PO { get; set; }
        public string MA_DON_PO { get; set; }
    
        public virtual BH_CT_DON_HANG_PO BH_CT_DON_HANG_PO { get; set; }
        public virtual BH_DON_HANG_PO BH_DON_HANG_PO { get; set; }
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual HH HH { get; set; }
        public virtual KH KH { get; set; }
    }
}
