//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_HANG_CAN_GIU
    {
        public int ID { get; set; }
        public int ID_PO_BAN { get; set; }
        public string MA_HANG { get; set; }
        public int SL_CAN_GIU { get; set; }
        public bool DA_GIU { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual BH_CT_DON_HANG_PO BH_CT_DON_HANG_PO { get; set; }
        public virtual HH HH { get; set; }
    }
}
