//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_XL_YEU_CAU_HOI_GIA
    {
        public int ID { get; set; }
        public Nullable<int> ID_YEU_CAU_HOI_GIA { get; set; }
        public string MA_HANG { get; set; }
        public string MA_KHACH_ORDER { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public string MA_NCC { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string THOI_GIAN_CAP_HANG { get; set; }
        public System.DateTime NGAY_HOI_GIA { get; set; }
        public string GHI_CHU { get; set; }
        public string PUR_XU_LY { get; set; }
        public string TRUC_THUOC { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual MH_YEU_CAU_HOI_GIA MH_YEU_CAU_HOI_GIA { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
