//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_YEU_CAU_HOI_GIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_YEU_CAU_HOI_GIA()
        {
            this.MH_XL_YEU_CAU_HOI_GIA = new HashSet<MH_XL_YEU_CAU_HOI_GIA>();
        }
    
        public int ID { get; set; }
        public string MA_HANG { get; set; }
        public string MA_CHUAN { get; set; }
        public string MA_KHACH_ORDER { get; set; }
        public string THONG_SO { get; set; }
        public string HANG { get; set; }
        public string SALES_YEU_CAU { get; set; }
        public string PUR_XU_LY { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public string GHI_CHU { get; set; }
        public System.DateTime NGAY_HOI_GIA { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public string TRUC_THUOC { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN1 { get; set; }
        public virtual HH_NHOM_VTHH HH_NHOM_VTHH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_XL_YEU_CAU_HOI_GIA> MH_XL_YEU_CAU_HOI_GIA { get; set; }
    }
}
