//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC_LIEN_HE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NCC_LIEN_HE()
        {
            this.MH_DE_NGHI_NHAP_KHO = new HashSet<MH_DE_NGHI_NHAP_KHO>();
            this.MH_PO_MUA_HANG = new HashSet<MH_PO_MUA_HANG>();
            this.NCC_PUR_PHU_TRACH = new HashSet<NCC_PUR_PHU_TRACH>();
        }
    
        public int ID_LIEN_HE { get; set; }
        public string MA_NHA_CUNG_CAP { get; set; }
        public string NGUOI_LIEN_HE { get; set; }
        public string CHUC_VU { get; set; }
        public string PHONG_BAN { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string SO_DIEN_THOAI_1 { get; set; }
        public string SO_DIEN_THOAI_2 { get; set; }
        public string EMAIL_CA_NHAN { get; set; }
        public string EMAIL_CONG_TY { get; set; }
        public string SKYPE { get; set; }
        public string FACEBOOK { get; set; }
        public string GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_DE_NGHI_NHAP_KHO> MH_DE_NGHI_NHAP_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_PO_MUA_HANG> MH_PO_MUA_HANG { get; set; }
        public virtual NCC NCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NCC_PUR_PHU_TRACH> NCC_PUR_PHU_TRACH { get; set; }
    }
}
