//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST_COMMENTS
    {
        public int ID { get; set; }
        public int ID_BAIVIET_KINHDOANH { get; set; }
        public string NGUOI_BINH_LUAN { get; set; }
        public System.DateTime NGAY_BINH_LUAN { get; set; }
        public string NOI_DUNG_BINH_LUAN { get; set; }
    
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual POST_KINHDOANH POST_KINHDOANH { get; set; }
    }
}
