//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST_KINHDOANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST_KINHDOANH()
        {
            this.POST_COMMENTS = new HashSet<POST_COMMENTS>();
        }
    
        public int ID { get; set; }
        public string NGUOI_DANG { get; set; }
        public System.DateTime NGAY_DANG { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public string DANH_MUC_DANG_BAI { get; set; }
        public string NOI_DUNG_DANG { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST_COMMENTS> POST_COMMENTS { get; set; }
    }
}
